# Generated by Django 4.2 on 2023-05-11 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Auth_Code',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('for_user', models.CharField(max_length=255)),
                ('send_time', models.TimeField()),
                ('send_date', models.TimeField()),
                ('auth_code', models.CharField(max_length=5)),
                ('max_test', models.IntegerField()),
                ('last_test_time', models.TimeField()),
                ('last_test_date', models.DateField()),
            ],
        ),
        migrations.AddField(
            model_name='user',
            name='active',
            field=models.BooleanField(null=True),
        ),
    ]
