# Generated by Django 4.2 on 2023-05-13 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_auth_code_user_active'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Auth_Code',
        ),
        migrations.AddField(
            model_name='user',
            name='auth_link',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
