# Generated by Django 4.2 on 2023-05-30 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_delete_auth_code_user_auth_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='recovery_link',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
